### ISSUE TITLE
Error thrown with no explanation

### ISSUE THREAD

**Issue by kevinbioj** [extensionsapp/translatte#5]
Hey,
There's an ongoing issue that has been existing forever on the old version of the module (`google-translate-api`) that is still not fixed here, so I post the issue here so this new version (that seems to be actually maintained) becomes better.
I am running on Ubuntu 18.04 LTS and I use node.js v8.10 in my production site. When I use the module (with as example `translatte('Hello', { to: 'fr' })`) I am getting this:

```
Error
    at /home/---/---/node_modules/translatte/index.js:141:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Nothing else, just an "Error" that I don't know the source.
Hope you can do something, thanks :wave:

**Edit** - Printing the original error object seems to show that it's actually a *403 Forbidden* error that is thrown by Google when the request is being made, beginning of the HTML response:
```
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
```

**Comment by extensionsapp** [comment]
Try the new version.

**Comment by ElhamAryanpur** [comment]
Have you tried setting user agents? Normally it give that error without proper user agent
